COLOR_FONDO = "#1E1E1E"
COLOR_BOTON = "#3A3F44"
COLOR_TEXTO = "#FFFFFF"
COLOR_BOTON_OPERACION = "#FF4081"

FUENTE_PANTALLA = ("Montserrat", 24, "bold")
FUENTE_BOTONES = ("Inter", 18, "bold")

COLOR_BOTON_CIENTIFICO = "#7C4DFF"



